// src/app/components/footer/footer.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { LogoComponent } from '../logo/logo.component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [LogoComponent],
  changeDetection: ChangeDetectionStrategy.Eager,
  templateUrl: './footer.component.html',
})
export class FooterComponent {
  readonly year = new Date().getFullYear();

  readonly footerLinks = [
    { href: '#services', label: 'Services' },
    { href: '#why', label: 'Why Us' },
    { href: '#stats', label: 'Results' },
    { href: '#support', label: 'Support' },
    { href: '#team', label: 'Our Team' },
    { href: '#contact', label: 'Contact' },
  ];
}

<footer class="site-footer">
  <div class="container footer-inner">
    <div class="footer-brand">
      <app-logo variant="footer" />
      <p>Protecting what matters most, around the clock.</p>
    </div>
    <div class="footer-links">
      @for (link of footerLinks; track link.href) {
        <a [href]="link.href">{{ link.label }}</a>
      }
    </div>
  </div>
  <div class="container footer-bottom">
    <span>© {{ year }} Jama Go Security. All rights reserved.</span>
    <span>SIA Licensed • Fully Insured</span>
  </div>
</footer>

// src/components/Footer.jsx
import Logo from "./Logo.jsx";

const FOOTER_LINKS = [
  { href: "#services", label: "Services" },
  { href: "#why", label: "Why Us" },
  { href: "#stats", label: "Results" },
  { href: "#support", label: "Support" },
  { href: "#team", label: "Our Team" },
  { href: "#contact", label: "Contact" },
];

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="site-footer">
      <div className="container footer-inner">
        <div className="footer-brand">
          <Logo variant="footer" />
          <p>Protecting what matters most, around the clock.</p>
        </div>
        <div className="footer-links">
          {FOOTER_LINKS.map((link) => (
            <a key={link.href} href={link.href}>
              {link.label}
            </a>
          ))}
        </div>
      </div>
      <div className="container footer-bottom">
        <span>© {year} Jama Go Security. All rights reserved.</span>
        <span>SIA Licensed • Fully Insured</span>
      </div>
    </footer>
  );
}
