// src/app/components/header/header.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  ElementRef,
  ViewChildren,
  QueryList,
  AfterViewInit,
  ChangeDetectionStrategy
} from '@angular/core';
import { LogoComponent } from '../logo/logo.component';
import { NAV_ITEMS } from '../../data/nav.data';
import {
  isNavDropdown,
  NavDropdownItem,
  NavItem,
  NavLink,
} from '../../models/nav.model';
import {
  CLOSE_DELAY_MS,
  DESKTOP_MQ,
  isPointerInSafeZone,
} from '../../utils/mega-menu.utils';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [LogoComponent],
  changeDetection: ChangeDetectionStrategy.Eager,
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit, AfterViewInit, OnDestroy {
  readonly navItems = NAV_ITEMS;

  mobileOpen = false;
  activeHash = '#top';
  openDropdown: string | null = null;
  isDesktopNav = true;

  @ViewChildren('dropdownEl') dropdownEls!: QueryList<ElementRef<HTMLElement>>;

  private closeTimer: ReturnType<typeof setTimeout> | null = null;
  private dropdownMap = new Map<string, HTMLElement>();
  private mediaQuery = window.matchMedia(DESKTOP_MQ);
  private onHashChange = () => this.syncHash();
  private onMediaChange = (e: MediaQueryListEvent) => {
    this.isDesktopNav = e.matches;
  };
  private onMouseMove = (e: MouseEvent) => this.handleMouseMove(e);
  private onPointerDown = (e: PointerEvent) => this.handlePointerDown(e);
  private onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') this.closeDropdown();
  };

  ngOnInit(): void {
    this.syncHash();
    this.isDesktopNav = this.mediaQuery.matches;
    window.addEventListener('hashchange', this.onHashChange);
    this.mediaQuery.addEventListener('change', this.onMediaChange);
    document.addEventListener('keydown', this.onKeyDown);
  }

  ngAfterViewInit(): void {
    this.rebuildDropdownMap();
    this.dropdownEls.changes.subscribe(() => this.rebuildDropdownMap());
    document.addEventListener('mousemove', this.onMouseMove, { passive: true });
    document.addEventListener('pointerdown', this.onPointerDown);
  }

  ngOnDestroy(): void {
    this.cancelClose();
    window.removeEventListener('hashchange', this.onHashChange);
    this.mediaQuery.removeEventListener('change', this.onMediaChange);
    document.removeEventListener('keydown', this.onKeyDown);
    document.removeEventListener('mousemove', this.onMouseMove);
    document.removeEventListener('pointerdown', this.onPointerDown);
  }

  isDropdown(item: NavItem): item is NavDropdownItem {
    return isNavDropdown(item);
  }

  asColumns(children: NavLink[] | NavLink[][]): NavLink[][] {
    return children as NavLink[][];
  }

  asLinks(children: NavLink[] | NavLink[][]): NavLink[] {
    return children as NavLink[];
  }

  flattenChildren(children: NavLink[] | NavLink[][]): NavLink[] {
    if (Array.isArray(children[0])) {
      return (children as NavLink[][]).flat();
    }
    return children as NavLink[];
  }

  isActive(href: string, hash = this.activeHash): boolean {
    if (href === '#top') return hash === '#top' || hash === '';
    return hash === href;
  }

  childIsActive(item: NavDropdownItem): boolean {
    const siblings = this.flattenChildren(item.children);
    return siblings.some((c) => this.isMegaLinkActive(c, siblings));
  }

  isMegaLinkActive(child: NavLink, siblings: NavLink[]): boolean {
    if (!this.isActive(child.href)) return false;
    const duplicates = siblings.filter((item) => item.href === child.href);
    return duplicates.length === 1;
  }

  onDropdownEnter(label: string): void {
    if (!this.isDesktopNav) return;
    this.cancelClose();
    this.openDropdown = label;
  }

  onDropdownLeave(): void {
    if (!this.isDesktopNav) return;
    this.scheduleClose();
  }

  onDropdownBlur(event: FocusEvent, label: string): void {
    if (!this.isDesktopNav) return;
    const current = event.currentTarget as HTMLElement;
    if (!current.contains(event.relatedTarget as Node)) {
      this.scheduleClose();
    }
  }

  toggleMobileDropdown(label: string): void {
    this.openDropdown = this.openDropdown === label ? null : label;
  }

  closeMobile(): void {
    this.mobileOpen = false;
    this.closeDropdown();
  }

  toggleMobileMenu(): void {
    this.mobileOpen = !this.mobileOpen;
  }

  private syncHash(): void {
    this.activeHash = window.location.hash || '#top';
  }

  private rebuildDropdownMap(): void {
    this.dropdownMap.clear();
    this.dropdownEls.forEach((ref) => {
      const label = ref.nativeElement.dataset['label'];
      if (label) this.dropdownMap.set(label, ref.nativeElement);
    });
  }

  private cancelClose(): void {
    if (this.closeTimer) {
      clearTimeout(this.closeTimer);
      this.closeTimer = null;
    }
  }

  private closeDropdown(): void {
    this.cancelClose();
    this.openDropdown = null;
  }

  private scheduleClose(): void {
    this.cancelClose();
    this.closeTimer = setTimeout(() => {
      this.openDropdown = null;
      this.closeTimer = null;
    }, CLOSE_DELAY_MS);
  }

  private handleMouseMove(e: MouseEvent): void {
    if (!this.openDropdown || !this.isDesktopNav) return;
    const activeEl = this.dropdownMap.get(this.openDropdown);
    if (!activeEl) return;
    if (isPointerInSafeZone(e.clientX, e.clientY, activeEl)) {
      this.cancelClose();
    }
  }

  private handlePointerDown(e: PointerEvent): void {
    if (!this.openDropdown || !this.isDesktopNav) return;
    const activeEl = this.dropdownMap.get(this.openDropdown);
    if (activeEl && !activeEl.contains(e.target as Node)) {
      this.closeDropdown();
    }
  }
}

<header class="site-header" [class.open]="mobileOpen" id="top">
  <div class="container header-inner">
    <a href="#top" class="brand" aria-label="Jama Go Security home" (click)="closeMobile()">
      <app-logo variant="header" />
    </a>

    <nav class="main-nav" aria-label="Main navigation">
      @for (item of navItems; track item.label) {
        @if (isDropdown(item)) {
          <div
            #dropdownEl
            [attr.data-label]="item.label"
            class="nav-dropdown"
            [class]="'nav-dropdown nav-dropdown--' + item.menu"
            [class.open]="openDropdown === item.label"
            [class.active]="childIsActive(item)"
            (mouseenter)="onDropdownEnter(item.label)"
            (mouseleave)="onDropdownLeave()"
            (focusin)="onDropdownEnter(item.label)"
            (focusout)="onDropdownBlur($event, item.label)"
          >
            <button
              type="button"
              class="nav-link nav-link--dropdown"
              [attr.aria-expanded]="openDropdown === item.label"
              aria-haspopup="true"
              (click)="!isDesktopNav && toggleMobileDropdown(item.label)"
            >
              {{ item.label }}
              <span class="nav-caret" aria-hidden="true"></span>
            </button>

            <div class="nav-mega">
              @if (item.menu === 'columns') {
                <div class="nav-mega-grid nav-mega-grid--2">
                  @for (column of asColumns(item.children); track column[0].label) {
                    <div class="nav-mega-col">
                      @for (child of column; track child.label) {
                        <a
                          [href]="child.href"
                          class="nav-mega-link"
                          [class.active]="isMegaLinkActive(child, column)"
                          (click)="closeMobile()"
                        >
                          {{ child.label }}
                        </a>
                      }
                    </div>
                  }
                </div>
              } @else if (item.menu === 'grid') {
                <div class="nav-mega-grid nav-mega-grid--3">
                  @for (child of asLinks(item.children); track child.label) {
                    <a
                      [href]="child.href"
                      class="nav-mega-link"
                      [class.active]="isMegaLinkActive(child, asLinks(item.children))"
                      (click)="closeMobile()"
                    >
                      {{ child.label }}
                    </a>
                  }
                </div>
              } @else {
                <div class="nav-mega-stack">
                  @for (child of asLinks(item.children); track child.label) {
                    <a
                      [href]="child.href"
                      class="nav-mega-link"
                      [class.active]="isMegaLinkActive(child, asLinks(item.children))"
                      (click)="closeMobile()"
                    >
                      {{ child.label }}
                    </a>
                  }
                </div>
              }
            </div>
          </div>
        } @else {
          <a
            [href]="item.href"
            class="nav-link"
            [class.active]="isActive(item.href)"
            (click)="closeMobile()"
          >
            {{ item.label }}
          </a>
        }
      }
    </nav>

    <a href="#contact" class="btn btn-primary btn-sm nav-cta" (click)="closeMobile()">
      Get a Quote
    </a>

    <button
      class="nav-toggle"
      aria-label="Toggle menu"
      [attr.aria-expanded]="mobileOpen"
      (click)="toggleMobileMenu()"
    >
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
</header>

// src/components/Header.jsx
import { useEffect, useState } from "react";
import useMegaMenu from "../hooks/useMegaMenu.js";
import Logo from "./Logo.jsx";

const SOLUTIONS_LEFT = [
  { href: "#surveillance-cctv", label: "Surveillance (CCTV) Systems" },
  { href: "#smart-home", label: "Smart Home & Automation" },
  { href: "#intercom", label: "Intercom System" },
  { href: "#smart-door-lock", label: "Smart Door Lock" },
  { href: "#telephone", label: "Telephone Systems" },
  { href: "#speed-gates", label: "Speed Gates & Turnstiles" },
  { href: "#metal-detector", label: "Metal Detector" },
  { href: "#moi-approval", label: "MOI Approval" },
  { href: "#cctv-drawing", label: "CCTV Drawing" },
];

const SOLUTIONS_RIGHT = [
  { href: "#access-control", label: "Access Control Systems" },
  { href: "#installation", label: "Installation & Maintenance" },
  { href: "#ceiling-sound", label: "Ceiling Sound System" },
  { href: "#internet-wifi", label: "Internet & Wi-Fi" },
  { href: "#central-satellite", label: "Central Satellite" },
  { href: "#gate-barriers", label: "Gate Barriers" },
  { href: "#accessories", label: "Accessories" },
  { href: "#amc-services", label: "AMC Services" },
  { href: "#free-consultation", label: "Free Consultation" },
];

const NAV_ITEMS = [
  { href: "#top", label: "Home" },
  {
    label: "About",
    menu: "stack",
    children: [
      { href: "#why", label: "Why Us" },
      { href: "#contact", label: "About Us" },
      { href: "#stats", label: "Our Results" },
    ],
  },
  {
    label: "Services",
    menu: "grid",
    children: [
      { href: "#manned-guarding", label: "Manned Guarding" },
      { href: "#mobile-patrols", label: "Mobile Patrols" },
      { href: "#event-security", label: "Event Security" },
      { href: "#cctv-monitoring", label: "CCTV Monitoring" },
      { href: "#residential-security", label: "Residential Security" },
      { href: "#alarm-response", label: "Alarm Response" },
    ],
  },
  {
    label: "Solutions",
    menu: "columns",
    children: [SOLUTIONS_LEFT, SOLUTIONS_RIGHT],
  },
  {
    label: "Projects",
    menu: "stack",
    children: [
      { href: "#moi-projects", label: "MOI Projects" },
      { href: "#non-moi-projects", label: "Non - Moi Projects" },
    ],
  },
  { href: "#blog", label: "Blog" },
  { href: "#support", label: "Support" },
  { href: "#contact", label: "Contact" },
];

function flattenChildren(children) {
  if (!children) return [];
  if (Array.isArray(children[0])) return children.flat();
  return children;
}

function isActive(href, activeHash) {
  if (!href) return false;
  if (href === "#top") return activeHash === "#top" || activeHash === "";
  return activeHash === href;
}

function childIsActive(item, activeHash) {
  return flattenChildren(item.children).some((c) =>
    isMegaLinkActive(c, flattenChildren(item.children), activeHash)
  );
}

function isMegaLinkActive(child, siblings, activeHash) {
  if (!isActive(child.href, activeHash)) return false;
  const duplicates = siblings.filter((item) => item.href === child.href);
  return duplicates.length === 1;
}

function DropdownLinks({ items, activeHash, onNavigate }) {
  return items.map((child) => (
    <a
      key={child.label}
      href={child.href}
      className={`nav-mega-link${isMegaLinkActive(child, items, activeHash) ? " active" : ""}`}
      onClick={onNavigate}
    >
      {child.label}
    </a>
  ));
}

export default function Header() {
  const [open, setOpen] = useState(false);
  const [activeHash, setActiveHash] = useState("#top");

  const {
    openDropdown,
    setOpenDropdown,
    isDesktopNav,
    closeDropdown,
    getDropdownHandlers,
  } = useMegaMenu();

  useEffect(() => {
    const syncHash = () => setActiveHash(window.location.hash || "#top");
    syncHash();
    window.addEventListener("hashchange", syncHash);
    return () => window.removeEventListener("hashchange", syncHash);
  }, []);

  const closeMobile = () => {
    setOpen(false);
    closeDropdown();
  };

  const toggleMobileDropdown = (label) => {
    setOpenDropdown((prev) => (prev === label ? null : label));
  };

  return (
    <header className={`site-header${open ? " open" : ""}`} id="top">
      <div className="container header-inner">
        <a href="#top" className="brand" aria-label="Jama Go Security home">
          <Logo variant="header" />
        </a>

        <nav className="main-nav" aria-label="Main navigation">
          {NAV_ITEMS.map((item) =>
            item.children ? (
              <div
                key={item.label}
                {...getDropdownHandlers(item.label)}
                className={`nav-dropdown nav-dropdown--${item.menu}${
                  openDropdown === item.label ? " open" : ""
                }${childIsActive(item, activeHash) ? " active" : ""}`}
              >
                <button
                  type="button"
                  className="nav-link nav-link--dropdown"
                  aria-expanded={openDropdown === item.label}
                  aria-haspopup="true"
                  onClick={() => {
                    if (!isDesktopNav) toggleMobileDropdown(item.label);
                  }}
                >
                  {item.label}
                  <span className="nav-caret" aria-hidden="true" />
                </button>

                <div className="nav-mega">
                  {item.menu === "columns" ? (
                    <div className="nav-mega-grid nav-mega-grid--2">
                      {item.children.map((column) => (
                        <div className="nav-mega-col" key={column[0].label}>
                          <DropdownLinks
                            items={column}
                            activeHash={activeHash}
                            onNavigate={closeMobile}
                          />
                        </div>
                      ))}
                    </div>
                  ) : item.menu === "grid" ? (
                    <div className="nav-mega-grid nav-mega-grid--3">
                      <DropdownLinks
                        items={item.children}
                        activeHash={activeHash}
                        onNavigate={closeMobile}
                      />
                    </div>
                  ) : (
                    <div className="nav-mega-stack">
                      <DropdownLinks
                        items={item.children}
                        activeHash={activeHash}
                        onNavigate={closeMobile}
                      />
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <a
                key={item.label}
                href={item.href}
                className={`nav-link${isActive(item.href, activeHash) ? " active" : ""}`}
                onClick={closeMobile}
              >
                {item.label}
              </a>
            )
          )}
        </nav>

        <a href="#contact" className="btn btn-primary btn-sm nav-cta">
          Get a Quote
        </a>

        <button
          className="nav-toggle"
          aria-label="Toggle menu"
          aria-expanded={open}
          onClick={() => setOpen((v) => !v)}
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </header>
  );
}
